<?php
//-------------------------------------------------------------------------------
//
//   This notice must remain untouched at all times. aaa
//   Copyright Alucio Net Technologies 2006. All rights reserved.
//   By Alucio Net Technologies.  Last modified 03-07-2006.
//
//   This script/code is owned and copyrighted by Alucio Net Technologies.
//   The following code cannot be duplicated, distributed, or modified
//   without prior agreements from Alucio Net Technologies. Violations to
//   this terms will be considered as criminal acts and the violators will
//   be persecuted to the maximum possible extent by the governing laws.
//
//   Author           : Junaidi Halin
//   Date created     : 06/12/06
//
//   Modifications history:
//      - 06/12/06 JHALIN Ported file and removed web services links
//
//-------------------------------------------------------------------------------
?>
<?php

$site_name = "messaging";
$site_address="https://{$site_name}.fekusa.xyz";

// Global Parameters

?>
